CREATE DATABASE IF NOT EXISTS archive;
CREATE DATABASE IF NOT EXISTS employeement;
CREATE DATABASE IF NOT EXISTS patientRecords;
CREATE DATABASE IF NOT EXISTS patientRegistration;
CREATE DATABASE IF NOT EXISTS hospitalManagementSystem;


